plugins:
  - jekyll-redirect-from

# Site settings
title: Nathan Tornquist.com
name: Nathan Tornquist
author: Nathan Tornquist
email: contact@tornquist.me
description: >
  Nathan Tornquist's personal website: a collection of projects and essays.
baseurl: ""
url: "http://nathantornquist.com"
permalink: /blog/:year/:month/:title/

# Build settings
markdown: kramdown
highlighter: rouge

# Site Variables
home_title: Home

copyright: Copyright &copy; Nathan Tornquist 2010-2023

collections:
  projects:
    output: true
    permalink: /projects/:title/
  privacy:
    output: true
    permalink: /privacy/:title/

exclude: [temp, scripts, .github]
